services:
  # mysqli extension
  mysqli:
    dockerfile: "RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli"

  # install composer. just installs it
  composer:
    dockerfile: |
           RUN apt-get install -y --no-install-recommends git zip unzip wget
           COPY templates/scripts/composer_install.sh /app/composer_install.sh
           RUN bash /app/composer_install.sh

  xdebug:
    dockerfile: |
           RUN yes | pecl install xdebug \
               && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" >> /usr/local/etc/php/php.ini \
               && echo "xdebug.mode=coverage" > /usr/local/etc/php/conf.d/xdebug.ini \
               && echo "xdebug.client_host=127.0.0.1" >> /usr/local/etc/php/conf.d/xdebug.ini \
               && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini
